version: '3.2'

services:

  gryvatorrelay:
    image: gryvatorrelay:0.1.17
    container_name: 'gryvatorrelay'
    volumes:
      - "./Volumes/Data:/Workspace/Data"
      - "./Volumes/Logs:/var/log/tor"
    ports:
      - 9001:9001
    environment:
      - nickname=MyNickname
      - orport=9001
      - exitrelay=0
      - socksport=0
      - controlsocket=0
      - contactinfo=tor-relay-maintainer@example.org
      - lognotice=true
      - logdebug=false
      - relaybandwidthrate=2000 KBytes
